apiVersion: apps/v1
kind: Deployment
metadata:
  name: delozo-ecommerce
  labels:
    app: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: golang-container
          image: arundas285/delozo
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom: 
                secretKeyRef: 
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-congifmap
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-congifmap
                  key: postgres-port

---
apiVersion: v1
kind: Service
metadata: 
  name:  deployement-service
spec:
  selector:
    app: ecommerce
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
       

