version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - ecommerce-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arundas285/ecommerce
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgresdb    
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - ecommerce-network
  
volumes:
  database:
networks:
  ecommerce-network:
    driver: bridge