version: '3.9'
services:
  app:
    image: arundas285/delozo
    container_name: golang_container
    env_file:
      - .env
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - learning
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - learning
volumes:
  database:
networks:
  learning:
    driver: bridge