apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  postgres-password: QXJ1bkAxNDM1  # base64 encoded value of 'Arun@1435'
  postgres-db: cG9zdGdyZXM= # base64 encoded value of 'postgres'
